---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/RedundantReturn:
  Exclude:
  - lib/avm/eac_ruby_base1/rubocop/gemfile.rb
Style/StringConcatenation:
  Exclude:
  - lib/avm/eac_ruby_base1/source_generators/base.rb
  - lib/avm/eac_ruby_base1/sources/namespace_replacer.rb
  - lib/avm/eac_ruby_base1/sources/runners/bundler/gemfile_local.rb
  - lib/avm/eac_ruby_base1/sources/runners/bundler/incompatible.rb
