inherit_gem:
  eac_ruby_gem_support: .rubocop.yml

AllCops:
  Exclude:
    - sub/**/*

Gemspec/DevelopmentDependencies:
  Exclude:
  - eac_tools.gemspec

Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
