require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - sub/**/*
    - spec/lib/avm/tools/runner/ruby/gems/generate_spec_files/**/*
  TargetRailsVersion: 5.2
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper/eac_launcher.rb'

Layout/LineLength:
  Max: 100

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Exclude:
    - spec/lib/avm/launcher/ruby/gem/build_spec.rb
    - spec/lib/avm/projects/stereotypes/git_subrepo/publish_spec.rb

Rails/DynamicFindBy:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec:
  Exclude:
    - spec/lib/avm/launcher/context_spec.rb
    - spec/lib/avm/launcher/git/base_spec.rb
    - spec/lib/avm/launcher/ruby/gem/build_spec.rb
    - spec/lib/avm/launcher/ruby/gem/specification_spec.rb
    - spec/lib/avm/launcher/vendor/github_spec.rb
    - spec/lib/avm/projects/stereotypes/git_subrepo/publish_spec.rb
    - spec/lib/avm/projects/stereotypes/git_subrepo/warp_spec.rb
    - spec/lib/avm/projects/stereotypes/ruby_gem_spec.rb
    - spec/lib/avm/projects/stereotypes/ruby_gem/publish_spec.rb

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
