---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/RedundantFetchBlock:
  Exclude:
  - template/avm/eac_rails_base0/source_generators/base/config/puma.rb
Style/RedundantFileExtensionInRequire:
  Exclude:
  - template/avm/eac_rails_base0/source_generators/base/config/application.rb
