# frozen_string_literal: true

begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

namespace :mygem do
  desc 'A stub task.'
  task :stub do # rubocop:disable Rails/RakeEnvironment
    puts 'Stub!'
  end
end
