---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/lib/avm/eac_ubuntu_base0/docker_image_spec.rb
  - spec/lib/avm/eac_ubuntu_base0/runners/base/docker_spec.rb
  - spec/lib/avm/eac_ubuntu_base0/runners/base_spec.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
