---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Gemspec/RequiredRubyVersion:
  Exclude:
  - avm-eac_postgresql_base0.gemspec
Layout/LineEndStringConcatenationIndentation:
  Exclude:
  - lib/avm/eac_postgresql_base0/instance/data_unit.rb
Layout/MultilineMethodCallIndentation:
  Exclude:
  - lib/avm/eac_postgresql_base0/instance/assert.rb
  - lib/avm/eac_postgresql_base0/instance/commands.rb
  - lib/avm/eac_postgresql_base0/instance/data_unit.rb
Rails/CompactBlank:
  Exclude:
  - lib/avm/eac_postgresql_base0/instance/data_unit.rb
Rails/SquishedSQLHeredocs:
  Exclude:
  - lib/avm/eac_postgresql_base0/instance/assert.rb
Style/OptionalBooleanParameter:
  Exclude:
  - lib/avm/eac_postgresql_base0/instance/commands.rb
Style/RedundantConstantBase:
  Exclude:
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
Style/StringConcatenation:
  Exclude:
  - lib/avm/eac_postgresql_base0/instance/data_unit.rb
