---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Gemspec/RequiredRubyVersion:
  Exclude:
  - avm-eac_php_base0.gemspec
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/lib/avm/eac_php_base0/file_formats/base_spec.rb
  - spec/lib/avm/eac_php_base0/source_generators/base_spec.rb
  - spec/lib/avm/eac_php_base0/sources/base_spec.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
Style/StringConcatenation:
  Exclude:
  - lib/avm/eac_php_base0/executables.rb
