inherit_gem:
  eac_ruby_gem_support: .rubocop.yml

Gemspec/DevelopmentDependencies:
  Exclude:
  - avm-eac_redmine_base0.gemspec

Style/StringConcatenation:
  Exclude:
  - lib/avm/eac_redmine_base0/sources/core_update.rb
