inherit_gem:
  eac_ruby_gem_support: .rubocop.yml

Gemspec/DevelopmentDependencies:
  Exclude:
  - avm-eac_redmine_base0.gemspec

Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/lib/avm/eac_redmine_base0/instances/apache_host_spec.rb
  - spec/lib/avm/eac_redmine_base0/instances/base/gitolite_spec.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb

Style/StringConcatenation:
  Exclude:
  - lib/avm/eac_redmine_base0/sources/core_update.rb
