inherit_gem:
  eac_ruby_gem_support: .rubocop.yml

Gemspec/DevelopmentDependencies:
  Exclude:
  - avm-eac_redmine_base0.gemspec

Layout/LineEndStringConcatenationIndentation:
  Exclude:
  - lib/avm/eac_redmine_base0/instances/rest_api/entity_base.rb

RSpec/FilePath:
  Exclude:
  - spec/lib/avm/eac_redmine_base0/instances/base/gitolite_spec.rb

RSpec/SpecFilePathFormat:
  Exclude:
  - spec/lib/avm/eac_redmine_base0/instances/base/gitolite_spec.rb

Style/FetchEnvVar:
  Exclude:
  - lib/avm/eac_redmine_base0/instances/docker_image.rb

Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/lib/avm/eac_redmine_base0/instances/apache_host_spec.rb
  - spec/lib/avm/eac_redmine_base0/instances/base/gitolite_spec.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb

Style/StringConcatenation:
  Exclude:
  - lib/avm/eac_redmine_base0/sources/core_update.rb
