---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Layout/MultilineMethodCallIndentation:
  Exclude:
  - lib/avm/eac_github_base0/api/entity.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/avm/eac_github_base0/application_scms/base_spec.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
