---
inherit_gem:
  eac_rails_gem_support: ".rubocop.yml"
AllCops:
  Exclude:
  - sub/**/*
  - public/uploads/**/*
Gemspec/RequiredRubyVersion:
  Exclude:
  - engines/*/*.gemspec
Metrics/BlockLength:
  Exclude:
  - db/schema.rb
