# frozen_string_literal: true

source 'https://rubygems.org'

gem 'eac_rails_base0'
gem 'eac_rails_gem_support', group: :development

# Local gems
::Dir["#{__dir__}/{sub/gems,engines}/*/*.gemspec"].each do |file|
  gem ::File.basename(::File.dirname(file)), path: ::File.dirname(file)
end
