---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/OpenStructUse:
  Exclude:
  - lib/avm/git/launcher/base/dirty_files.rb
Style/RedundantArgument:
  Exclude:
  - lib/avm/git/issue/complete/commits.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - lib/avm/git/issue.rb
  - spec/lib/avm/git/commit/diff_tree_line_spec.rb
  - spec/lib/avm/git/commit_spec.rb
  - spec/lib/avm/git/launcher/base_spec.rb
  - spec/lib/avm/git/scms/git/commit/deploy_spec.rb
  - spec/lib/avm/git/scms/git_spec.rb
  - spec/lib/avm/git/scms/git_subrepo_spec.rb
  - spec/lib/avm/git/vendor/github_spec.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
Style/RedundantRegexpEscape:
  Exclude:
  - lib/avm/git/launcher/base/subrepo.rb
  - lib/avm/git/scms/git/commit.rb
Style/SafeNavigation:
  Exclude:
  - lib/avm/git/launcher/publish_base.rb
Style/StringConcatenation:
  Exclude:
  - lib/avm/git/subrepo_check/show_result.rb
