---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Lint/MissingSuper:
  Exclude:
  - lib/eac_cli/runner/exit.rb
Lint/RedundantCopDisableDirective:
  Exclude:
  - lib/eac_cli/runner/instance_methods.rb
  - lib/eac_cli/speaker/list.rb
Lint/UselessMethodDefinition:
  Exclude:
  - lib/eac_cli/config.rb
Naming/VariableNumber:
  Exclude:
  - spec/lib/eac_cli/runner/for_context_spec.rb
RSpec/BeEq:
  Exclude:
  - spec/lib/eac_cli/runner/for_context_spec.rb
  - spec/lib/eac_cli/runner_spec.rb
  - spec/lib/eac_cli/runner_with/subcommands_spec.rb
RSpec/FilePath:
  Exclude:
  - spec/lib/eac_cli/runner/for_context_spec.rb
RSpec/IndexedLet:
  Exclude:
  - spec/lib/eac_cli/runner/for_context_spec.rb
RSpec/MultipleMemoizedHelpers:
  Exclude:
  - spec/lib/eac_cli/runner/for_context_spec.rb
  - spec/lib/eac_cli/runner_with/output_spec.rb
RSpec/SpecFilePathFormat:
  Exclude:
  - spec/lib/eac_cli/runner/for_context_spec.rb
Rails/CompactBlank:
  Exclude:
  - lib/eac_cli/runner_with/help/builder/alternative.rb
  - lib/eac_cli/runner_with/help/builder.rb
Rails/Exit:
  Exclude:
  - lib/eac_cli/runner/class_runner.rb
Style/ArgumentsForwarding:
  Exclude:
  - lib/eac_cli/runner/context_responders/set.rb
Style/EmptyLiteral:
  Exclude:
  - lib/eac_cli/runner_with_set.rb
Style/GlobalStdStream:
  Exclude:
  - lib/eac_cli/speaker/options.rb
Style/OpenStructUse:
  Exclude:
  - lib/eac_cli/speaker/list.rb
Style/OptionalBooleanParameter:
  Exclude:
  - lib/eac_cli/definition.rb
  - lib/eac_cli/runner/exit.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - eac_cli.gemspec
  - lib/eac_cli/core_ext.rb
  - lib/eac_cli/patches/object.rb
  - lib/eac_cli/patches.rb
  - spec/lib/eac_cli/definition/alternative_spec.rb
  - spec/lib/eac_cli/old_configs_spec.rb
  - spec/lib/eac_cli/parser/alternative_spec.rb
  - spec/lib/eac_cli/runner/for_context_spec.rb
  - spec/lib/eac_cli/runner_spec.rb
  - spec/lib/eac_cli/runner_with/confirmation_spec.rb
  - spec/lib/eac_cli/runner_with/help/layout_spec.rb
  - spec/lib/eac_cli/runner_with/help_spec.rb
  - spec/lib/eac_cli/runner_with/output_spec.rb
  - spec/lib/eac_cli/runner_with/subcommands_spec.rb
  - spec/lib/eac_cli/speaker_spec.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
Style/RedundantFilterChain:
  Exclude:
  - lib/eac_cli/parser.rb
Style/RedundantInitialize:
  Exclude:
  - lib/eac_cli/config.rb
Style/RedundantReturn:
  Exclude:
  - lib/eac_cli/speaker.rb
