---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Gemspec/RequiredRubyVersion:
  Exclude:
  - avm-files.gemspec
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
