---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Layout/LineEndStringConcatenationIndentation:
  Exclude:
  - lib/avm/eac_rails_base1/instances/runners/tasks_scheduler/systemd_unit.rb
  - lib/avm/eac_rails_base1/runner_with/rails_environment.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
