#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require 'bundler/setup'
rescue Gem::LoadError, Bundler::GemfileNotFound, Bundler::GemNotFound
  nil
end
require 'eac_tools'
EacTools::Runner.run
