---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Rails/SquishedSQLHeredocs:
  Exclude:
  - lib/avm/eac_wordpress_base0/instances/base.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/lib/avm/eac_wordpress_base0/instances/apache_host_spec.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
