---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Layout/MultilineMethodCallIndentation:
  Exclude:
  - lib/avm/eac_latex_base0/sources/build/copy_files.rb
  - lib/avm/eac_latex_base0/sources/build.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
Style/RedundantParentheses:
  Exclude:
  - lib/avm/eac_latex_base0/sources/build.rb
Style/StringConcatenation:
  Exclude:
  - lib/avm/eac_latex_base0/executables.rb
  - lib/avm/eac_latex_base0/sources/build/file/chapter_index.rb
