---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/StringConcatenation:
  Exclude:
  - lib/avm/eac_latex_base0/executables.rb
  - lib/avm/eac_latex_base0/sources/build/file/chapter_index.rb
