---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Lint/RedundantCopDisableDirective:
  Exclude:
  - spec/lib/avm/eac_asciidoctor_base0/instances/build/document_spec.rb
Naming/VariableNumber:
  Exclude:
  - spec/lib/avm/eac_asciidoctor_base0/instances/build/document_spec.rb
Rails/CompactBlank:
  Exclude:
  - lib/avm/eac_asciidoctor_base0/instances/build/document/header_lines.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/lib/avm/eac_asciidoctor_base0/file_formats/base_spec.rb
  - spec/lib/avm/eac_asciidoctor_base0/instances/build/document_spec.rb
  - spec/lib/avm/eac_asciidoctor_base0/instances/build_spec.rb
  - spec/lib/avm/eac_asciidoctor_base0/source_generators/base_spec.rb
  - spec/lib/avm/eac_asciidoctor_base0/sources/base_spec.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper/eac_asciidoctor_base0_stubs.rb
  - spec/spec_helper.rb
