---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Layout/MultilineMethodCallIndentation:
  Exclude:
  - lib/avm/eac_redmine_plugin_base0/sources/init_file.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/lib/avm/eac_redmine_plugin_base0/sources/init_file_spec.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
